// 导出所有字典文件
export * from './typing';
export * from './enum';
export * from './dict';
export * from './dictEntrust';
export * from './dictFutures';
export * from './dictInfo';
export * from './dictRiskAlarm';
export * from './offerAccseeDict';

// 为了方便使用，可以导出一些常用的字典类型
export type {
  DictFeKeyEnumType,
  DictCodeEnumType,
  SecurityCategoryItem,
} from './dict';

export type { DictType } from './dictFutures';

// 为了方便使用，提供一个默认导出对象
const Dicts = {
  // 从 dict.ts 导出
  OPERATION_TYPES,
  DATA_TYPES,
  COMPARE_DIRECTIONS,
  COMPARE_DIRECTIONS__MAP,
  ALARM_REACTIONS,
  GRAY_FLAG,
  ALARM_REACTIONS__MAP,
  UNITS,
  UNITS__MAP,
  RULE_STATUSES,
  RULE_STATUSES__MAP,
  RULE_TYPE_LEVEL_1,
  RULE_TYPE_LEVEL_2,
  RULE_RELATION_TYPES,
  RULE_CHECK_POINT_TYPES,
  LIFT_AND_SUPPRESSION_CALCULATION_TYPES,
  CALCULATION_TIME_WINDOW,
  REVERSE_CALCULATION_TIME_WINDOW,
  BLOCK_ORDER_TYPES,
  ENTRUST_DIRECTION,
  ENTRUST_TYPE,
  CONTROL_TYPE,
  IDENTIFY_CONDITION,
  EXEMPT_PRICE_TYPE,
  SECURITY_CONTROL_TYPES,
  SECURITY_CONTROL_TYPES__MAP,
  GROUP_CONTROL_TYPES__MAP,
  DENOM_TYPES__MAP,
  SECURITY_AGGREGATION_METHODS,
  SECURITY_AGGREGATION__MAP,
  TRADING_MARKETS,
  SECURITY_CATEGORY_LEVEL_1,
  SECURITY_CATEGORY_LEVEL_2,
  RULE_CONTROL_DIM,
  DIMENSION_CONTROL_TYPES,
  DIMENSION_CONTROL_TYPES__MAP,
  SECU_POOL_TYPES,
  ENTRUST_DIRECTION_TYPES,
  PROCEDURE_STATUS,
  PROCEDURE_TYPE,
  POSITION_TYPE,
  ADJUST_TYPE,
  SECURITY_CATEGORY_LEVEL,
  transformDictCodeToNameHelper,
  transformDictFeKeyToCodeHelper,
  getReferNodes,

  // 从 dictEntrust.ts 导出
  ENTRUST_TYPE: ENTRUST_TYPE as typeof ENTRUST_TYPE,
  ENTRUST_DIRECTION: ENTRUST_DIRECTION as typeof ENTRUST_DIRECTION,
  ENTRUST_STATUS,
  PENDING_ENTRUST_STATUS,
  INVEST_TYPE,
  PRICE_TYPE,
  TRADE_PLATFORM_ID,
  BUSINESS_TYPE,
  ETF_POR_TYPE,

  // 从 dictFutures.ts 导出
  MONTH_CONTROL_TYPE,
  COMTRACT_MONTH,
  COMPARE_DIRECTION,
  BEGIN_INFLUENCE_DIRECTION,
  END_INFLUENCE_DIRECTION,
  MONTH_OFFSET,
  MONTH_OFFSET_KEY,
  DAY_OFFSET,
  DAY_TYPE,
  THRESHOLD_TYPE,
  TRADING_MARKETS: TRADING_MARKETS as typeof TRADING_MARKETS,

  // 从 dictInfo.ts 导出
  TRADE_MARKET,
  TRADE_MARKET_PRECIOUS_METALS,
  TRADE_MARKET_REPO,
  TRADE_MARKET_INDEX,
  TRADE_MARKET_STOCK,
  TRADE_MARKET_FUND,
  TRADE_MARKET_BONDS,
  TRADE_MARKET_FUTURE,
  TRADE_MARKET_OPTION,
  TRADE_UNIT_TYPE,
  TRADE_STATUS,
  BOARD_TYPE,
  CURRENCY_TYPE,
  QUOTE_UNIT,
  DELIVERY_METHOD,
  SETTLE_METHOD,
  CASH_REPLACE_FLAG,
  FUND_INVEST_CLASS,
  FUND_ISSUE_TYPE,
  FUND_RISK_PROFIT_TYPE,
  FUND_INVEST_NATURE,
  ARBITRAGE_TYPE,
  OPTION_TYPE,
  INFORMATION_SOURCE,

  // 从 dictRiskAlarm.ts 导出
  OPERATION_TYPE_I1,
  CALC_MODE_F1,

  // 从 offerAccseeDict.ts 导出
  OFFER_CHANNEL_tYPE,
  OFFER_TRADING_MARKETS,

  // 从 enum.ts 导出
  FUNC_TYPE,
  USE_AUTH,
};

export default Dicts;